paths :
    input_folder_name : data/input/
    output_folder_name : data/output/
    path_to_kaggle_scripts : data/input/scripts_kaggle/
    path_to_imsdb_scripts : data/input/scripts_imsdb/
    topic_modeling_folder : topic_modeling/
    pronoun_folder : pronouns/

names :
    kaggle_db_name : bechdel_script_kaggle.csv
    imsdb_db_name : bechdel_script_imsdb.csv
    imsdb_intermediate_name : list_script_imsdb.csv
    bechdel_db_name : bechdel_db.csv
    db_name : dataset.csv
    list_of_words_about_men : keywords.json
    list_pronoun_tokens : pronouns.csv

merge_dataset :
    keep : imsdb  # imsdb ou kaggle

urls : 
    bechdel_test_api : http://bechdeltest.com/api/v1/getAllMovies
    imsdb_base_url : http://www.imsdb.com

bechdel_test_rules :
    only_women_in_whole_scene : false           # these two parameters can take values (true, true), (true, false), (false, false)
    whole_discussion_not_about_men : false      # For now we forbid (false, true) for reasons of bechdel test coherence as well as implementation complexity  

    # in case "whole_discussion_not_about_men" or "only_women_in_whole_scene" is false 
    # "lines_of_dialogues_in_a_row" is a parameter that indicates the number of successive feminie lines to validate 
    # criteria 2 or 3 when they are set to soft
    lines_of_dialogues_in_a_row : 2 # minimum 2

used_methods :
    character_gender_method : narrative # can also be classify