paths :
    input_folder_name : data/input/
    path_to_kaggle_scripts : data/input/scripts_kaggle/
    path_to_imsdb_scripts : data/input/scripts_imsdb/

names :
    kaggle_db_name : bechdel_script_kaggle.csv
    imsdb_db_name : bechdel_script_imsdb.csv
    imsdb_intermediate_name : list_script_imsdb.csv
    bechdel_db_name : bechdel_db.csv
    db_name : dataset.csv

merge_dataset :
    keep : imsdb ## imsdb ou kaggle

urls : 
    bechdel_test_api : http://bechdeltest.com/api/v1/getAllMovies
    imsdb_base_url : http://www.imsdb.com