paths :
    input_folder_name : data/input/
    path_to_kaggle_scripts : data/input/scripts_kaggle/
    path_to_imsdb_scripts : data/input/scripts_imsdb/
    topic_modeling_folder : topic_modeling/
    script_parsing_folder : script_parsing/
    script_parsing_experiments_folder : script_parsing/experiments

names :
    kaggle_db_name : bechdel_script_kaggle.csv
    imsdb_db_name : bechdel_script_imsdb.csv
    imsdb_intermediate_name : list_script_imsdb.csv
    bechdel_db_name : bechdel_db.csv
    db_name : dataset.csv
    list_of_words_about_men : keywords.json
    coherently_parsed_scripts : coherent_parsing.csv
    tagged_lines : tagged_lines.csv

merge_dataset :
    keep : imsdb ## imsdb ou kaggle

script_parsing_model:
    pretrained_model_name: bert-base-uncased
    dataset_percentage: 0.1
    fully_connected_hidden_layers : [1024, 512, 128]
    nb_output_classes : 6
    validation_dataset_proportion: 0.3
    test_dataset_proportion: 0.1
    seed: 42
    batch_size : 50
    learning_rate : 0.01
    nb_epochs : 2
    

urls : 
    bechdel_test_api : http://bechdeltest.com/api/v1/getAllMovies
    imsdb_base_url : http://www.imsdb.com