paths :
    input_folder_name : data/input/
    output_folder_name : data/output/
    path_to_kaggle_scripts : data/input/scripts_kaggle/
    path_to_imsdb_scripts : data/input/scripts_imsdb/
    topic_modeling_folder : topic_modeling/
    pronoun_folder : gender/
    script_parsing_folder : script_parsing/
    script_parsing_experiments_folder : script_parsing/experiments

names :
    kaggle_db_name : bechdel_script_kaggle.csv
    imsdb_db_name : bechdel_script_imsdb.csv
    imsdb_intermediate_name : list_script_imsdb.csv
    bechdel_db_name : bechdel_db.csv
    db_name : dataset.csv
    list_of_words_about_men : keywords.json
    list_pronoun_tokens : pronouns.csv
    list_prenoms : Prenoms.csv
    coherently_parsed_scripts : coherent_parsing.csv
    tagged_lines : tagged_lstripped_lines.csv
    dataset_embeddings : dataset_embeddings.pt
    parsing_model : parsing_model.pth
    unparsable_scripts : dataset_building/unparsable_scripts.yaml

merge_dataset :
    keep : imsdb  # 'imsdb' or 'kaggle'

script_parsing_model:
    model_architecture : 
        use_sentence_transformer: true
        bert_pretrained_model_name: bert-base-uncased
        sentence_transformer_pretrained_model_name: all-MiniLM-L6-v2
        fully_connected_hidden_layers : [2048, "relu", 1024, "relu", 512, "relu", 256, "relu", 128]
        nb_output_classes : 6
    load_checkpoint: false
    checkpoint_path: ""
    intermediate_forward: true 
    dataset_percentage: 0.1
    validation_dataset_proportion: 0.3
    test_dataset_proportion: 0.1
    seed: 42
    batch_size : 50
    learning_rate : 
        initial_value: 0.01
        decrease_on_plateau: true
        patience: 3
    weight_decay: 0.0001
    nb_epochs : 50
    
urls : 
    bechdel_test_api : http://bechdeltest.com/api/v1/getAllMovies
    imsdb_base_url : http://www.imsdb.com

bechdel_test_rules :
    only_women_in_whole_scene : false           # these two parameters can take values (true, true), (true, false), (false, false)
    whole_discussion_not_about_men : false      # For now we forbid (false, true) for reasons of bechdel test coherence as well as implementation complexity  

    # in case "whole_discussion_not_about_men" or "only_women_in_whole_scene" is false 
    # "lines_of_dialogues_in_a_row" is a parameter that indicates the number of successive feminie lines to validate 
    # criteria 2 or 3 when they are set to soft
    lines_of_dialogues_in_a_row : 2 # minimum 2

used_methods :
    character_gender_method : coref # can also be classify or coref or narrative
    reparse_with_ml: true # will reparse the script with ml if the naive parsing is incoherent
